### ISSUE TITLE
Use POSIX compliant C

### ISSUE THREAD

**Issue by comcloudway** [Thomas-Wilde/SE24#1]
As far as I can tell, this project isn't using POSIX C.

See [here](https://pubs.opengroup.org/cgi/susv5search.cgi?KEYWORDS=u_char&SUBSTRING=substring&CONTEXT=%28%2Fbasedefs%2F%29) and [here](https://stackoverflow.com/a/1918960)

This is why the project fails to build on Alpine Linux:
```
make
[-33%] Building CXX object CMakeFiles/ImageGenerator.dir/main.cc.o
/storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc: In function 'void createImage(std::ifstream&, int, int, const std::vector<Color>&)':
/storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc:89:3: error: 'u_char' was not declared in this scope; did you mean 'putchar'?
   89 |   u_char *data = new u_char[width * height * 3];
      |   ^~~~~~
      |   putchar
/storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc:89:11: error: 'data' was not declared in this scope; did you mean 'std::data'?
   89 |   u_char *data = new u_char[width * height * 3];
      |           ^~~~
      |           std::data
In file included from /usr/include/c++/14.2.0/string:53,
                 from /usr/include/c++/14.2.0/bits/locale_classes.h:40,
                 from /usr/include/c++/14.2.0/bits/ios_base.h:41,
                 from /usr/include/c++/14.2.0/ios:44,
                 from /usr/include/c++/14.2.0/istream:40,
                 from /usr/include/c++/14.2.0/fstream:40,
                 from /storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc:1:
/usr/include/c++/14.2.0/bits/range_access.h:344:5: note: 'std::data' declared here
  344 |     data(initializer_list<_Tp> __il) noexcept
      |     ^~~~
/storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc:89:22: error: 'u_char' does not name a type; did you mean 'char'?
   89 |   u_char *data = new u_char[width * height * 3];
      |                      ^~~~~~
      |                      char
/storage/self/primary/Documents/uni/sem5/se/aufgaben/a03/SE24/task01/c++/main.cc:108:3: error: type '<type error>' argument given to 'delete', expected pointer
  108 |   delete[] data;
      |   ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/ImageGenerator.dir/build.make:76: CMakeFiles/ImageGenerator.dir/main.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ImageGenerator.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

As far as I can tell, changing `u_char` to `char` fixes this. 
Edit: `uint8_t` appears to be the correct datatype to use.

**Comment by Thomas-Wilde** [comment]
changed u_char to char.
Thanks for the hint.

**Comment by comcloudway** [comment]
Thanks for the quick response.✨

Follow up: I had a look at wikipedia and it shows the [`char`](https://en.m.wikipedia.org/wiki/C_data_types#Main_types) range as either *-127 - 127* or *0 - 255*.

After looking at the [`glibc source`](https://sourceware.org/git/?p=glibc.git;a=blob;f=posix/bits/types.h;h=34e001ad68938039f6aad15f881cdede2554bba4;hb=HEAD#l31], I found that `u_char` is an alias to `unsigned char`.

I've tried compiling it with `unsigned char` instead of `u_char` which seems to be working as well.
According to a [glibc commit](https://sourceware.org/git/?p=glibc.git;a=commit;h=11160cb76f56e0a711686e34881a4eaf1ad2fa0e) this would have been the correct fix - seems like `char` works in this case too though (maybe C automatically determines the signedness at compile time)

Sorry for the confusion, just thought I'd follow up with this 🌸
